const sampleItinenrary = [
  {
    title: "Adventure in the Alps",
    description: "Experience the thrill of breathtaking mountain landscapes, offering opportunities for skiing, hiking, and mountaineering. Discover charming villages, savor local delicacies, and immerse yourself in the rich regional culture. Whether you're seeking adventure or serenity, this itinerary provides something for everyone. Plan an unforgettable journey that promises memories to last a lifetime.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 80000,
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-08"),
    activities: "Skiing, snowboarding, mountain hiking.",
    accommodation: "Ski lodges and mountain cabins.",
    transport: "Flights to Zurich, local trains and buses.",
  },
  {
    title: "Cultural Exploration of Japan",
    description: "Immerse yourself in rich traditions and vibrant history, exploring ancient temples, serene gardens, and bustling markets. Delight in exquisite cuisine, from sushi to ramen, and experience traditional arts such as tea ceremonies and calligraphy. Discover a unique blend of old and new in every corner, offering a deep dive into cultural heritage. This journey invites you to explore beauty, tradition, and modernity.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 100000,
    startDate: new Date("2024-11-05"),
    endDate: new Date("2024-11-19"),
    activities: "Temple visits, tea ceremonies, traditional crafts.",
    accommodation: "Ryokan and modern hotels.",
    transport: "Flights, Shinkansen, local trains.",
  },
  {
    title: "Safari in Kenya",
    description: "Embark on an exhilarating journey through stunning landscapes, where you can witness majestic wildlife in their natural habitat. Enjoy game drives, encounter diverse species, and experience the rich traditions of local cultures. This itinerary offers a perfect blend of adventure and relaxation, providing an unforgettable experience. Immerse yourself in the beauty and excitement of a safari adventure that will leave you in awe.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 90000,
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-11"),
    activities: "Game drives, cultural visits, nature walks.",
    accommodation: "Luxury lodges and tented camps.",
    transport: "Flights and guided safari vehicles.",
  },
  {
    title: "Historic Europe Tour",
    description: "Step back in time with a captivating exploration through historic Europe. Wander through ancient cities, marvel at iconic landmarks, and delve into rich cultural heritage. This itinerary combines stunning architecture with engaging historical narratives, offering a unique journey through Europe's past. Immerse yourself in the charm and grandeur of historic sites and create lasting memories of a remarkable adventure.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 150000,
    startDate: new Date("2024-10-10"),
    endDate: new Date("2024-10-25"),
    activities: "Museum visits, guided city tours, historic site exploration.",
    accommodation: "Boutique hotels and historic inns.",
    transport: "Flights, trains, and buses.",
  },
  {
    title: "Island Hopping in the Caribbean",
    description: "Embark on a vibrant island-hopping adventure across the Caribbean, where turquoise waters and sun-kissed beaches await. Discover diverse cultures, savor tropical flavors, and explore lush landscapes as you sail from one picturesque island to the next. Each stop offers unique experiences, from serene beaches to lively local markets. This journey promises relaxation, adventure, and unforgettable moments in paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 250000,
    startDate: new Date("2024-07-15"),
    endDate: new Date("2024-07-25"),
    activities: "Beach time, snorkeling, island tours.",
    accommodation: "Beachfront resorts.",
    transport: "Flights, ferries, and boat transfers.",
  },
  {
    title: "Australian Outback Adventure",
    description:"Venture into the rugged beauty of the Australian Outback, where vast red deserts and striking rock formations create a dramatic landscape. Experience the thrill of off-road exploration, witness stunning sunsets, and immerse yourself in the rich indigenous culture of the region. From exploring ancient caves to spotting unique wildlife, this adventure promises an unforgettable journey through one of the world's most remote and captivating terrains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 90000,
    startDate: new Date("2024-08-20"),
    endDate: new Date("2024-08-30"),
    activities: "Camping, wildlife viewing, cultural experiences.",
    accommodation: "Camping under the stars.",
    transport: "Flights, 4x4 vehicles.",
  },
  {
    title: "Romantic Paris Getaway",
    description: "Venture into the rugged beauty of the Australian Outback, where vast red deserts and striking rock formations create a dramatic landscape. Experience the thrill of off-road exploration, witness stunning sunsets, and immerse yourself in the rich indigenous culture of the region. From exploring ancient caves to spotting unique wildlife, this adventure promises an unforgettable journey through one of the world's most remote and captivating terrains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 50000,
    startDate: new Date("2024-02-14"),
    endDate: new Date("2024-02-19"),
    activities: "Eiffel Tower, Seine river cruise, gourmet dining.",
    accommodation: "Luxury hotels.",
    transport: "Flights and local transport.",
  },
  {
    title: "The Great Wall and Beyond",
    description: "Embark on a journey through the majestic expanse of the Great Wall, marveling at its ancient fortifications and stunning views. Explore the rich history and cultural heritage of the surrounding regions, discovering traditional villages and local cuisine. From hiking along the wall's historic sections to delving into the vibrant stories of ancient China, this itinerary offers a captivating blend of history, culture, and natural beauty.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 80000,
    startDate: new Date("2024-05-10"),
    endDate: new Date("2024-05-22"),
    activities: "Great Wall, Forbidden City, Terracotta Army.",
    accommodation: "Modern hotels.",
    transport: "Flights, bullet trains, buses.",
  },
  {
    title: "Discovering the Wonders of Egypt",
    description: "Unveil the mysteries of ancient civilization with a journey through Egypt. Wander among the towering pyramids of Giza and the majestic Sphinx, explore the treasures of the Egyptian Museum, and cruise the Nile to witness the grandeur of temples like Karnak and Luxor. Immerse yourself in a land where history and legend intertwine, offering an unforgettable experience rich in culture and discovery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 750000,
    startDate: new Date("2024-03-05"),
    endDate: new Date("2024-03-13"),
    activities: "Pyramids, Nile cruise, museums.",
    accommodation: "Luxury hotels and cruise ship.",
    transport: "Flights, river cruise, local transport.",
  },
  {
    title: "Wildlife and Beaches of Costa Rica",
    description:"Immerse yourself in the vibrant ecosystems of Costa Rica with this adventure. Explore lush rainforests teeming with diverse wildlife, including monkeys, toucans, and sloths. Relax on pristine beaches with crystal-clear waters and stunning sunsets. Experience the perfect blend of natural beauty and tropical relaxation, making for a memorable and invigorating escape.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 40000,
    startDate: new Date("2024-06-10"),
    endDate: new Date("2024-06-18"),
    activities: "Rainforest hikes, wildlife tours, beach relaxation.",
    accommodation: "Eco-lodges and beach resorts.",
    transport: "Flights, local transportation.",
  }
];

module.exports = { data: sampleItinenrary }
 